version: 2.1
description: test

jobs:
  test:
    executor: test
    steps:
      - checkout
      - run:
          name: echo
          command: echo 'this is test'

executors:
  test:
    docker:
    - image: circleci/node:11.3.0
